services:
  openolat:
   build: .
   ports:
     - "8080:8080"
   environment:
     - DB_HOST=postgres-db
     - DB_PORT=5432
     - DB_USERNAME=openolat
     - DB_PASSWORD=openolat
     - DB_NAME=openolat
   depends_on:
     - postgres-db
  
  # openolat-manuell:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.release-based
  #     args:
  #       OPENOLAT_VERSION: 2001
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_HOST=postgres-db
  #     - DB_PORT=5432
  #     - DB_USERNAME=openolat
  #     - DB_PASSWORD=openolat
  #     - DB_NAME=openolat
  #   depends_on:
  #     - postgres-db
  
  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: openolat
      POSTGRES_PASSWORD: openolat
      POSTGRES_DB: openolat
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: