deployment:
  image: ghcr.io/immxmmi/openolat
  tag: dev-latest
  replicas: 1


config:
  installationDir: "/home/openolat"
  logDir: "/home/openolat/logs"
  contextPath: "/openolat"
  domainName: "localhost"
  port: 8088
  sslPort: 0
  smtpHost: "disabled"
  tomcatId: 1
  userdataDir: "/home/openolat/olatdata"
  # If userdataDirExistingVolumeClaimName is set, no VolumeClaim will be created
  userdataDirExistingVolumeClaimName: ""
  # Only used if userdataDirExistingVolumeClaimName is not set
  userdataDirVolumeSize: "1Gi"
  # Mail config
  smtp:
    host: ""
    port: 25
    user: ""
    pwd: ""
    sslEnabled: false
    sslCheckCertificate: false
    starttls: false
    timeout: 8000
    from:
  fromdomain: ""
  fromemail: "no-reply@frentix.com"
  fromname: "OpenOlat eLearning Server (${server.domainname})"
  adminemail: "webmaster@frentix.com"
  supportemail: "support@openolat.com"
  quotaemail: "${supportemail}"
  deleteuseremail: "${supportemail}"
  erroremail: "support@openolat.com"
  # Video config
  thumbnailProvider: "magick"
  videoTranscodingTasksetCpuconfig: "0,1"
  videoTranscodingResolutions: "1080,720"
  av:
    videoRecordingEnabled: true
    audioRecordingEnabled: true
    localTranscodingEnabled: true
    localAudioConversionEnabled: true
    handbrakecliPath: ""
    ffmpegPath: ""
  gotenbergUrl:

  oauth:
    useOauth: false
    clientId: ""
    clientSecret: ""
    oidcEp: ""
    context: ""
    realm: ""
    attributenameUseridentifyer: ""

database:
  host: "openolat-postgresql.openolat.svc.cluster.local"
  port: 5432
  name: "openolat"
  username: "openolat"
  password: "openolat"
  source: "jndi"
  jndi: "java:comp/env/jdbc/openolatDS"
  vendor: "postgresql"

resources:
  limits:
    memory: "10Gi"
    cpu: "4"
  requests:
    memory: "1Gi"
    cpu: "500m"

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

ingress:
  enabled: false
  hostname: "openolat.frentix.com"

secrets:
  useExternalSecrets: false
