deployment:
  image: ghcr.io/immxmmi/openolat
  tag: dev-latest
  replicas: 1
  db:
    host: "openolat-postgresql.openolat.svc.cluster.local"
    port: 5432
    name: "openolat"
    username: "openolat"
    password: "openolat"
  openolatConfig:
    db:
      source: "jndi"
      jndi: "java:comp/env/jdbc/openolatDS"
      vendor: "postgresql"
    installationDir: "/home/openolat"
    logDir: "/home/openolat/logs"
    contextPath: "/openolat"
    domainName: "localhost"
    port: 8088
    sslPort: 0
    smtpHost: "disabled"
    tomcatId: 1
    userdataDir: "/home/openolat/olatdata"
    userdataDirSize: "1Gi"
  resources:
    limits:
      memory: "10Gi"
      cpu: "4"
    requests:
      memory: "1Gi"
      cpu: "500m"

service:
  port: 8080

ingress:
  hostname: "openolat.frentix.com"