deployment:
  image: ghcr.io/immxmmi/openolat
  tag: dev-latest
  replicas: 1


config:
  installationDir: "/home/openolat"
  logDir: "/home/openolat/logs"
  contextPath: "/openolat"
  domainName: "localhost"
  port: 8088
  sslPort: 0
  smtpHost: "disabled"
  tomcatId: 1
  userdataDir: "/home/openolat/olatdata"
  # If userdataDirExistingVolumeClaimName is set, no VolumeClaim will be created
  userdataDirExistingVolumeClaimName: ""
  # Only used if userdataDirExistingVolumeClaimName is not set
  userdataDirVolumeSize: "1Gi"
  oauth:
    useOauth: false
    clientId: ""
    clientSecret: ""
    endpoint: ""

database:
  host: "openolat-postgresql.openolat.svc.cluster.local"
  port: 5432
  name: "openolat"
  username: "openolat"
  password: "openolat"
  source: "jndi"
  jndi: "java:comp/env/jdbc/openolatDS"
  vendor: "postgresql"

resources:
  limits:
    memory: "10Gi"
    cpu: "4"
  requests:
    memory: "1Gi"
    cpu: "500m"

service:
  port: 8080
  targetPort: 8080
  type: ClusterIP

ingress:
  enabled: false
  hostname: "openolat.frentix.com"

secrets:
  useExternalSecrets: false
