apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-openolat-config
  labels:
    {{- include "openolat.labels" . | nindent 4 }}
data:
  olat.properties: |
    db.source={{ .Values.database.source }}
    db.jndi={{ .Values.database.jndi }}
    db.vendor={{ .Values.database.vendor }}
    installation.dir={{ .Values.config.installationDir }}
    log.dir={{ .Values.config.logDir }}
    server.contextpath={{ .Values.config.contextPath }}
    server.domainname={{ .Values.config.domainName }}
    server.port={{ .Values.config.port }}
    server.port.ssl={{ .Values.config.sslPort }}
    smtp.host={{ .Values.config.smtpHost }}
    tomcat.id={{ .Values.config.tomcatId }}
    userdata.dir={{ .Values.config.userdataDir }}
    oauth.keycloak.context={{ .Values.config.oauth.context }}
    oauth.keycloak.realm={{ .Values.config.oauth.realm }}
    oauth.keycloak.attributename.useridentifyer={{ .Values.config.oauth.attributenameUseridentifyer }}