apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-openolat-config
  labels:
    {{- include "openolat.labels" . | nindent 4 }}
data:
  olat.properties: |
    db.source={{ .Values.deployment.openolatConfig.db.source }}
    db.jndi={{ .Values.deployment.openolatConfig.db.jndi }}
    db.vendor={{ .Values.deployment.openolatConfig.db.vendor }}
    installation.dir={{ .Values.deployment.openolatConfig.installationDir }}
    log.dir={{ .Values.deployment.openolatConfig.logDir }}
    server.contextpath={{ .Values.deployment.openolatConfig.contextPath }}
    server.domainname={{ .Values.deployment.openolatConfig.domainName }}
    server.port={{ .Values.deployment.openolatConfig.port }}
    server.port.ssl={{ .Values.deployment.openolatConfig.sslPort }}
    smtp.host={{ .Values.deployment.openolatConfig.smtpHost }}
    tomcat.id={{ .Values.deployment.openolatConfig.tomcatId }}
    userdata.dir={{ .Values.deployment.openolatConfig.userdataDir }}