apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    {{- include "{{ .Release.Name }}.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include (print .Release.Name ".selectorLabels") . | nindent 6 }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        {{- include (print .Release.Name ".selectorLabels") . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: 8080