{{- if not .Values.secrets.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: root-xml
  labels:
    {{- include "openolat.labels" . | nindent 4 }}
type: Opaque
stringData:
  xml-value: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <Context path="" docBase="/usr/local/tomcat/webapp" debug="0" reloadable="false" allowLinking="true">
    <Resource auth="Container" type="javax.sql.DataSource"
    maxTotal="16" maxIdle="4" maxWaitMillis="60000"
    username="{{ .Values.database.username }}"
    password="{{ .Values.database.password }}"
    name="jdbc/OpenOLATDS"
    driverClassName="org.postgresql.Driver"
    validationQuery="SELECT 1"
    validationQueryTimeout="-1"
    testOnBorrow="true" testOnReturn="false"
    url="jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}" />
    </Context>
{{- end }}