{{- if and (.Values.config.oauth.useOauth) (not .Values.secrets.useExternalSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
  labels:
    {{- include "openolat.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.config.oauth.clientId }}
  client-secret: {{ .Values.config.oauth.clientSecret }}
  endpoint: {{ .Values.config.oauth.endpoint }}
{{- end }}