apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openolat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/immxmmi/openolat
    chart: openolat
    targetRevision: 1.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: openolat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true