apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zot-registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://zotregistry.dev/helm-charts/
    chart: zot
    targetRevision: 0.1.67
    helm:
      values: |
        replicaCount: 1
        image:
          repository: ghcr.io/project-zot/zot-linux-amd64
          pullPolicy: IfNotPresent
          tag: "v2.1.2"
        service:
          type: NodePort
          port: 5000
        configFiles:
          config.json: |
            {
              "storage": { "rootDirectory": "/var/lib/registry" },
              "http": { "address": "0.0.0.0", "port": "5000" },
              "log": { "level": "debug" }
            }
  destination:
    server: https://kubernetes.default.svc
    namespace: zot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true